.\"
.hys 50
.TH "rancid-cvs" "1" "7 Jan 2004"
.SH NAME
rancid-cvs \- initialize CVS and rancid group files and directories
.SH SYNOPSIS
.B rancid-cvs
[group [group ...]]
.SH DESCRIPTION
.B rancid-cvs
is a
.IR sh (1)
script to create the directories,
.BR router.db (5),
and
.BR cvs (1)
directories necessary for a rancid group.
.\"
.PP
.B rancid-cvs
reads
.BR rancid.conf (5)
to configure itself.  Then proceeds with the initialization first of the
.BR cvs (1)
repository, if necessary, and then for each of the rancid groups listed on
the command-line or those in the variable
.I LIST_OF_GROUPS
from
.BR rancid.conf (5),
if the argument is omitted.
.\"
.PP
Running
.B rancid-cvs
for groups which already exist will not cause problems.  If the group's
directory already exists, the
.BR cvs (1)
import will be skipped, and if it's
.BR router.db (5)
already exists, it will be left as-is.
.\"
.PP
The best method for adding groups is add the group name to
.I LIST_OF_GROUPS
in
.BR rancid.conf (5),
then run
.B rancid-cvs.  Do not create the directories manually, allow rancid-cvs
to do it.
.\"
.SH "SEE ALSO"
.BR cvs (1),
.BR rancid.conf (5),
.BR router.db (5)
